name: AWS Deployment CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            echo "🚀 Starting Deployment..."

            cd ~/property-listing-platform || exit

            echo "📥 Pulling latest code..."
            git pull origin main

            echo "📝 Recreating .env file..."
            cat <<EOF > .env
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            PORT=5000
            DB_HOST=db
            DB_PORT=5432
            EOF

            echo "🔨 Building and starting containers..."
            docker-compose up -d --build

            echo "🧹 Cleaning unused images..."
            docker image prune -f

            echo "✅ Deployment Completed!"